### PR TITLE
Minor fix for Modal demo

### PR DESCRIPTION
**Pull request by crevete**

### CODE REVIEW

**Comment by sjardine** [comment]
I'm sure I'm missing something but could you explain why removeOnHide should be false? Does the demo not work she its true?

**Comment by crevete** [comment]
@sjardine Because it doesn't work without :-) In fact, in our demo page, modals are "hard coded" in the DOM, just like native bootstrap modal demo. They are not created and displayed "on the fly" by JavaScript. That's why before the setRemoveOnHide méthode os optional. Yes, it is not the default behavior of bootstrap.

**Comment by sjardine** [comment]
I don't think I like the need to specify removeOnHide whenever a modal is defined this way. What do you think @crevete?

**Comment by crevete** [comment]
@sjardine Yes, I seems a little strange. Two choices : 
* Revert your commit and make ```removeOnHide```optional, as bootstrap native behavior ; And add javadoc to tell developers the use case
* Keep your commit to make ```removeOnHide```as default to avoid issues like #394 ; but we need to specify ```removeOnHide``` whenever a modal is defined statically.

Maybe I have light preference with the first approach, how about you ?

**Comment by sjardine** [comment]
I will revert the change and document the class.

**Comment by crevete** [comment]
@sjardine Ok, so don't forget to leave a message in #394. Thanks

**Pull request merged**
