### PR TITLE
Updated demo.

### PR DESCRIPTION
**Pull request by sjardine**

### CODE REVIEW

**Comment by crevete** [comment]
@sjardine to update the demo, you have to update the ```gh-pages``` branch, but not the ```master``` branch...

**Comment by sjardine** [comment]
Yeah.  Thanks.  Still working on it.....

**Comment by sjardine** [comment]
Actually, I did specify the gh-pages branch for my forked repo and the main repo.  The changes were significant so they didn't merge well.

**Comment by sjardine** [comment]
OK.  Got it now.  Switch to gh-pages branch first, then pr from there.

**Comment by crevete** [comment]
Yeah exactly and you just need to update the snapshot directory.

**Pull request closed without merging**
